# Generated by Django 6.0.1 on 2026-01-24 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_rename_execution_ex_organiz_55ebd6_idx_execution_e_organiz_288cbc_idx_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        ('sandboxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this agent configuration', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional description of this configuration's purpose")),
                ('agent_type', models.CharField(choices=[('claude_code', 'Claude Code'), ('codex', 'Codex (OpenAI)'), ('opencode', 'OpenCode'), ('shelley', 'Shelley'), ('custom', 'Custom CLI Agent')], help_text='Type of external agent', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this agent configuration is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default config for its type')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Agent-specific credentials (API keys, tokens)')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Agent-specific settings (model, temperature, etc.)')),
                ('max_steps', models.PositiveIntegerField(default=50, help_text='Maximum steps/iterations per run')),
                ('timeout_seconds', models.PositiveIntegerField(default=600, help_text='Maximum execution time in seconds')),
                ('cli_command', models.CharField(blank=True, help_text='Custom CLI command to invoke the agent', max_length=500)),
                ('cli_args', models.JSONField(blank=True, default=list, help_text='Default CLI arguments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_agent_configs', to=settings.AUTH_USER_MODEL)),
                ('default_sandbox', models.ForeignKey(blank=True, help_text='Default sandbox config to use with this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_agent_configs', to='sandboxes.sandboxconfig')),
                ('organization', models.ForeignKey(help_text='The organization that owns this config', on_delete=django.db.models.deletion.CASCADE, related_name='external_agent_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'External Agent Config',
                'verbose_name_plural': 'External Agent Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique run identifier', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timed Out')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Status details or error message')),
                ('prompt', models.TextField(help_text='The prompt sent to the agent')),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt/instructions')),
                ('context_files', models.JSONField(blank=True, default=list, help_text='List of files provided as context')),
                ('response', models.TextField(blank=True, help_text="The agent's response")),
                ('output_stream', models.TextField(blank=True, help_text='Full output stream (for CLI agents)')),
                ('artifacts', models.JSONField(blank=True, default=list, help_text='List of artifacts (files created/modified, etc.)')),
                ('tokens_used', models.JSONField(blank=True, default=dict, help_text='Token usage breakdown (prompt, completion, total)')),
                ('steps_taken', models.PositiveIntegerField(default=0, help_text='Number of steps/iterations taken')),
                ('runtime_config', models.JSONField(blank=True, default=dict, help_text='Runtime configuration snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed', null=True)),
                ('config', models.ForeignKey(help_text='Configuration used for this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agent_wrappers.externalagentconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_agent_runs', to=settings.AUTH_USER_MODEL)),
                ('execution_run', models.ForeignKey(blank=True, help_text='Parent ExecutionRun if triggered by event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_agent_runs', to='execution.executionrun')),
                ('organization', models.ForeignKey(help_text='The organization that owns this run', on_delete=django.db.models.deletion.CASCADE, related_name='external_agent_runs', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project this run is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_agent_runs', to='projects.project')),
                ('sandbox_session', models.ForeignKey(blank=True, help_text='Sandbox session this run executed in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='sandboxes.sandboxsession')),
            ],
            options={
                'verbose_name': 'External Agent Run',
                'verbose_name_plural': 'External Agent Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalagentconfig',
            index=models.Index(fields=['organization', 'agent_type'], name='agent_wrapp_organiz_b4e65e_idx'),
        ),
        migrations.AddIndex(
            model_name='externalagentconfig',
            index=models.Index(fields=['organization', 'is_default'], name='agent_wrapp_organiz_ac0837_idx'),
        ),
        migrations.AddIndex(
            model_name='externalagentrun',
            index=models.Index(fields=['organization', '-created_at'], name='agent_wrapp_organiz_4c371f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalagentrun',
            index=models.Index(fields=['project', '-created_at'], name='agent_wrapp_project_1f2c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='externalagentrun',
            index=models.Index(fields=['status'], name='agent_wrapp_status_cc36c5_idx'),
        ),
        migrations.AddIndex(
            model_name='externalagentrun',
            index=models.Index(fields=['run_id'], name='agent_wrapp_run_id_9f979e_idx'),
        ),
    ]
