"""
Pydantic schemas for chat API.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request schema for chat endpoint."""

    message: str = Field(..., min_length=1, description="User message to send to the agent")
    agent_name: str = Field(
        default="ZoeaAssistant", description="Name of the agent to use"
    )
    instructions: str = Field(
        default="You are a helpful AI assistant for Zoea Studio.",
        description="System instructions for the agent",
    )
    conversation_id: int | None = Field(
        default=None,
        description="ID of existing conversation to continue (creates new if not provided)"
    )
    project_id: int | None = Field(
        default=None,
        description="ID of project (uses default if not provided)"
    )
    debug: bool = Field(
        default=False,
        description="Enable debug mode to see system instructions in response"
    )

    # Context parameters for agent routing
    view_type: str | None = Field(
        default=None,
        description="Current view type (chat, document_detail, document_editor, folder_view, excalidraw)",
    )
    document_id: int | None = Field(
        default=None,
        description="ID of the document being viewed/edited (for document context)",
    )
    document_ids: list[int] | None = Field(
        default=None,
        description="List of document IDs for multi-document context",
    )
    folder_id: int | None = Field(
        default=None,
        description="ID of folder for folder-scoped context",
    )
    collection_id: int | None = Field(
        default=None,
        description="ID of document collection/notebook",
    )
    rag_session_id: str | None = Field(
        default=None,
        description="ID of existing RAG session to use",
    )
    requested_capabilities: list[str] | None = Field(
        default=None,
        description="Requested agent capabilities (e.g., 'deep_research')",
    )


class MessageAttachmentItem(BaseModel):
    """Schema for an attachment on an email message."""

    id: int = Field(..., description="Attachment ID")
    filename: str = Field(..., description="Original filename")
    content_type: str | None = Field(None, description="MIME type of the attachment")
    size: int = Field(0, description="File size in bytes")
    url: str = Field(..., description="URL to access the attachment")


class ToolArtifactItem(BaseModel):
    """Schema for an artifact generated by a tool (e.g., image generation)."""

    type: str = Field(..., description="Artifact type: image, code, document, diagram, markdown")
    path: str = Field(..., description="File path to the artifact (or virtual path for inline content)")
    mime_type: str | None = Field(None, description="MIME type of the file")
    title: str | None = Field(None, description="Display title")
    url: str | None = Field(None, description="URL to access the artifact")
    content: str | None = Field(None, description="Inline content for markdown artifacts")


class ChatResponse(BaseModel):
    """Response schema for chat endpoint."""

    response: str = Field(..., description="Agent's response")
    agent_name: str = Field(..., description="Name of the agent that responded")
    conversation_id: int = Field(..., description="ID of the conversation")
    system_instructions: str | None = Field(
        default=None,
        description="System instructions sent to agent (only included if debug=true)"
    )
    organization: str | None = Field(
        default=None,
        description="Organization name (only included if debug=true)"
    )

    # Routing info (only included if debug=true)
    agent_type: str | None = Field(
        default=None,
        description="Agent type used (chat, document_rag, excalidraw, deep_research)",
    )
    tools_used: list[str] | None = Field(
        default=None,
        description="Tools that were available to the agent",
    )

    # Tool-generated artifacts (Issue #107)
    tool_artifacts: list[ToolArtifactItem] | None = Field(
        default=None,
        description="Artifacts generated by tools during this response (e.g., images)",
    )


class ConversationListItem(BaseModel):
    """Summary of a conversation for list view."""

    id: int = Field(..., description="Conversation ID")
    title: str = Field(..., description="Conversation title")
    agent_name: str = Field(..., description="Agent used in this conversation")
    message_count: int = Field(..., description="Total number of messages")
    created_at: datetime = Field(..., description="When the conversation was created")
    updated_at: datetime = Field(..., description="When the conversation was last updated")

    class Config:
        from_attributes = True


class ConversationListResponse(BaseModel):
    """Response schema for conversation list endpoint."""

    conversations: list[ConversationListItem] = Field(..., description="List of conversations")
    total: int = Field(..., description="Total number of conversations")


class MessageItem(BaseModel):
    """Schema for a single message in a conversation."""

    id: int = Field(..., description="Message ID")
    role: str = Field(..., description="Message role (user, assistant, system)")
    content: str = Field(..., description="Message content")
    created_at: datetime = Field(..., description="When the message was created")
    model_used: str | None = Field(None, description="Model used for assistant messages")
    tool_artifacts: list[ToolArtifactItem] | None = Field(
        None, description="Tool-generated artifacts for this message"
    )
    attachments: list[MessageAttachmentItem] | None = Field(
        None, description="Email attachments for this message (if from email)"
    )

    class Config:
        from_attributes = True


class ConversationDetailResponse(BaseModel):
    """Response schema for conversation detail endpoint."""

    id: int = Field(..., description="Conversation ID")
    title: str = Field(..., description="Conversation title")
    agent_name: str = Field(..., description="Agent used in this conversation")
    messages: list[MessageItem] = Field(..., description="List of messages in conversation")
    created_at: datetime = Field(..., description="When the conversation was created")
    updated_at: datetime = Field(..., description="When the conversation was last updated")
    email_thread_id: int | None = Field(
        None, description="ID of linked email thread (if conversation originated from email)"
    )


class ArtifactItem(BaseModel):
    """Schema for a single artifact item."""

    id: int = Field(..., description="Artifact item ID")
    source_channel: str = Field(..., description="Source channel (code, document, etc.)")
    source_metadata: dict = Field(default_factory=dict, description="Artifact metadata")
    preview: dict | None = Field(None, description="Preview data for rendering")
    is_pinned: bool = Field(False, description="Whether the artifact is pinned")
    created_at: datetime = Field(..., description="When the artifact was created")

    class Config:
        from_attributes = True


class ArtifactListResponse(BaseModel):
    """Response schema for conversation artifacts endpoint."""

    items: list[ArtifactItem] = Field(..., description="List of artifact items")
    total: int = Field(..., description="Total number of artifacts")
    collection_id: int | None = Field(None, description="ID of the artifact collection")
