# Generated by Django 6.0b1 on 2025-11-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipboard_type', models.CharField(choices=[('context', 'Context'), ('workspace', 'Workspace')], help_text='Clipboard category', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_recent', models.BooleanField(default=False)),
                ('mirror_to_workspace', models.BooleanField(default=True, help_text='When true, explicit additions to this clipboard are mirrored to the active workspace clipboard. Applies only to context clipboards.')),
                ('sequence_head', models.BigIntegerField(default=0, help_text='Tracks the head index for deque-style operations')),
                ('sequence_tail', models.BigIntegerField(default=-1, help_text='Tracks the tail index for deque-style operations')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User that owns/created the clipboard', on_delete=django.db.models.deletion.CASCADE, related_name='clipboards', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace that scopes this clipboard', on_delete=django.db.models.deletion.CASCADE, related_name='clipboards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-activated_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextClipboard',
            fields=[
            ],
            options={
                'verbose_name': 'Context Clipboard',
                'verbose_name_plural': 'Context Clipboards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('context_clipboards.clipboard',),
        ),
        migrations.CreateModel(
            name='WorkspaceClipboard',
            fields=[
            ],
            options={
                'verbose_name': 'Workspace Clipboard',
                'verbose_name_plural': 'Workspace Clipboards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('context_clipboards.clipboard',),
        ),
        migrations.CreateModel(
            name='VirtualClipboardNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('preview_text', models.TextField(blank=True)),
                ('preview_image', models.URLField(blank=True)),
                ('origin_reference', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('materialized_object_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_clipboard_nodes', to=settings.AUTH_USER_MODEL)),
                ('materialized_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_virtual_nodes', to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_clipboard_nodes', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClipboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(help_text='Relative ordering value supporting deque semantics')),
                ('direction_added', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5)),
                ('is_implicit', models.BooleanField(default=False, help_text='True when system-added (e.g., workspace drafts)')),
                ('is_pinned', models.BooleanField(default=False)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('source_channel', models.CharField(choices=[('conversation', 'Conversation'), ('message', 'Message'), ('document', 'Document'), ('workflow', 'Workflow'), ('canvas', 'Canvas'), ('code', 'Code Snippet'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clipboard_items_added', to=settings.AUTH_USER_MODEL)),
                ('clipboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='context_clipboards.clipboard')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('mirrored_from', models.ForeignKey(blank=True, help_text='Links workspace items back to the originating context item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirrored_items', to='context_clipboards.clipboarditem')),
                ('virtual_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clipboard_items', to='context_clipboards.virtualclipboardnode')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clipboard',
            index=models.Index(fields=['workspace', 'owner'], name='context_cli_workspa_70027b_idx'),
        ),
        migrations.AddIndex(
            model_name='clipboard',
            index=models.Index(fields=['clipboard_type', 'is_active'], name='context_cli_clipboa_6a9d2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='clipboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace', 'owner', 'clipboard_type'), name='unique_active_clipboard_per_user_and_type'),
        ),
        migrations.AddIndex(
            model_name='virtualclipboardnode',
            index=models.Index(fields=['workspace', 'node_type'], name='context_cli_workspa_0f724f_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualclipboardnode',
            index=models.Index(fields=['expires_at'], name='context_cli_expires_5832f0_idx'),
        ),
        migrations.AddIndex(
            model_name='clipboarditem',
            index=models.Index(fields=['clipboard', 'position'], name='context_cli_clipboa_38e556_idx'),
        ),
        migrations.AddIndex(
            model_name='clipboarditem',
            index=models.Index(fields=['is_implicit'], name='context_cli_is_impl_980820_idx'),
        ),
    ]
