# Generated by Django 6.0b1 on 2025-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_clipboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboarditem',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virtualclipboardnode',
            name='materialized_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
