# Generated by Django 6.0b1 on 2025-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_clipboards', '0003_remove_workspace_clipboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboarditem',
            name='preview',
            field=models.JSONField(blank=True, help_text='Custom preview data for the clipboard item (e.g., chat bubble, diagram thumbnail)', null=True),
        ),
    ]
