"""
Django settings for zoea project.

Generated by 'django-admin startproject' using Django 6.0b1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import tempfile
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Repository root is two levels up from zoea-core (packages/zoea-core -> repo root)
REPO_ROOT = BASE_DIR.parent.parent

# Load environment variables
load_dotenv(REPO_ROOT / ".env")

# Determine if we're in production (Render sets RENDER=true)
IS_PRODUCTION = os.getenv("RENDER", "").lower() == "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", 'django-insecure-r!bpsp0zv^h7143m1#^udm*8=vj_-))rl1z7_yif9dy4+s(plj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
    'corsheaders',
    'ninja',
    'mptt',
    'organizations',
    'allauth',  # django-allauth core
    'allauth.account',  # Registration and account management
    'accounts',
    'chat',
    'projects',
    'documents',
    'document_rag',
    'agents',
    'channels',
    'execution',
    'sources',
    'workflows',
    'events',
    'email_gateway',
    'flows',
    'platform_adapters',
    'sandboxes',
    'agent_wrappers',
    'output_dispatch',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by django-allauth
]

ROOT_URLCONF = 'zoea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zoea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

# Use DATABASE_URL if set (production/Supabase), otherwise SQLite for development
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Determine if this is a remote database (Supabase, etc.) that requires SSL
    # Local databases (localhost, 127.0.0.1) typically don't need SSL
    is_remote_db = not any(
        host in DATABASE_URL for host in ['localhost', '127.0.0.1', 'host.docker.internal']
    )

    # Use shorter connection lifetime for local dev to avoid exhausting connections
    # Production (remote) can use persistent connections
    conn_max_age = 600 if is_remote_db else 0

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=conn_max_age,
            conn_health_checks=True,
            ssl_require=is_remote_db,  # Only require SSL for remote databases
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user uploaded content)
# https://docs.djangoproject.com/en/dev/topics/files/
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenAI Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_CHAT_MODEL_ID = os.getenv("OPENAI_CHAT_MODEL_ID", "gpt-4o-mini")

# Gemini Configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL_ID = os.getenv("GEMINI_MODEL_ID", "gemini-2.5-flash")

# File Search Configuration
# Available backends: 'chromadb', 'gemini'
# The registry will use this value to select the default backend
FILE_SEARCH_BACKEND = os.getenv("FILE_SEARCH_BACKEND", "chromadb")
CHROMADB_PERSIST_DIRECTORY = os.getenv("CHROMADB_PERSIST_DIRECTORY")

# Image captioning (used for image indexing)
IMAGE_CAPTION_PROVIDER = os.getenv("IMAGE_CAPTION_PROVIDER", "openai")
IMAGE_CAPTION_MODEL = os.getenv("IMAGE_CAPTION_MODEL", "gpt-4o")
IMAGE_CAPTION_PROMPT = os.getenv("IMAGE_CAPTION_PROMPT")
FILE_SEARCH_MAX_TEXT_BYTES = int(os.getenv("FILE_SEARCH_MAX_TEXT_BYTES", 2 * 1024 * 1024))

# LLM Provider Configuration
# Default provider and model for chat/agent workflows
DEFAULT_LLM_PROVIDER = os.getenv("DEFAULT_LLM_PROVIDER", "openai")
DEFAULT_LLM_MODEL = os.getenv("DEFAULT_LLM_MODEL", "gpt-4o-mini")

# Local model endpoint (for Ollama, LM Studio, etc.)
LOCAL_MODEL_ENDPOINT = os.getenv("LOCAL_MODEL_ENDPOINT", "http://localhost:11434")

# Mailgun Configuration (for inbound email webhooks)
MAILGUN_API_KEY = os.getenv("MAILGUN_API_KEY")
MAILGUN_DOMAIN = os.getenv("MAILGUN_DOMAIN")

# Zoea Studio Settings
ZOEA_DEFAULT_THEME = os.getenv("ZOEA_DEFAULT_THEME", "ocean")

# Document Import Limits
ZOEA_IMPORT_MAX_FILE_SIZE_BYTES = int(
    os.getenv("ZOEA_IMPORT_MAX_FILE_SIZE_BYTES", 50 * 1024 * 1024)
)
ZOEA_IMPORT_MAX_TOTAL_SIZE_BYTES = int(
    os.getenv("ZOEA_IMPORT_MAX_TOTAL_SIZE_BYTES", 10 * 1024 * 1024 * 1024)
)
ZOEA_IMPORT_MAX_FILE_COUNT = int(
    os.getenv("ZOEA_IMPORT_MAX_FILE_COUNT", 100000)
)
ZOEA_IMPORT_MAX_DEPTH = int(os.getenv("ZOEA_IMPORT_MAX_DEPTH", 10))

_import_roots_raw = os.getenv("ZOEA_IMPORT_ALLOWED_ROOTS", "").strip()
if _import_roots_raw:
    _import_roots = (
        _import_roots_raw.split(",")
        if "," in _import_roots_raw
        else _import_roots_raw.split(os.pathsep)
    )
    ZOEA_IMPORT_ALLOWED_ROOTS = []
    for path in _import_roots:
        if not path.strip():
            continue
        candidate = Path(path.strip()).expanduser()
        if not candidate.is_absolute():
            candidate = (REPO_ROOT / candidate).resolve()
        ZOEA_IMPORT_ALLOWED_ROOTS.append(candidate)
else:
    ZOEA_IMPORT_ALLOWED_ROOTS = [
        Path.home(),
        Path(tempfile.gettempdir()),
    ]

# Agent Skills configuration
_skill_dirs_raw = os.getenv("ZOEA_SKILLS_DIRS", "").strip()
if _skill_dirs_raw:
    _skill_dirs = (
        _skill_dirs_raw.split(",")
        if "," in _skill_dirs_raw
        else _skill_dirs_raw.split(os.pathsep)
    )
    AGENT_SKILLS_DIRS = []
    for path in _skill_dirs:
        if not path.strip():
            continue
        candidate = Path(path.strip()).expanduser()
        if not candidate.is_absolute():
            candidate = (REPO_ROOT / candidate).resolve()
        AGENT_SKILLS_DIRS.append(candidate)
else:
    AGENT_SKILLS_DIRS = [REPO_ROOT / "skills"]

# CORS settings
# When using credentials (cookies), we cannot use CORS_ALLOW_ALL_ORIGINS
# Must specify exact origins when credentials are included
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True  # Required for session cookies

# Build CORS origins dynamically
ZOEA_FRONTEND_PORT = os.getenv("ZOEA_FRONTEND_PORT", "5173")
ZOEA_BACKEND_PORT = os.getenv("ZOEA_BACKEND_PORT", "8000")
FRONTEND_URL = os.getenv("FRONTEND_URL", "")
EXE_DEV_HOSTNAME = os.getenv("EXE_DEV_HOSTNAME", "")

# Development origins
CORS_ALLOWED_ORIGINS = [
    f"http://localhost:{ZOEA_FRONTEND_PORT}",
    f"http://127.0.0.1:{ZOEA_FRONTEND_PORT}",
    f"http://local.zoea.studio:{ZOEA_FRONTEND_PORT}",
]

# exe.dev VM origins (when EXE_DEV_HOSTNAME is set)
if EXE_DEV_HOSTNAME:
    CORS_ALLOWED_ORIGINS.extend([
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz",
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz:{ZOEA_FRONTEND_PORT}",
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz:{ZOEA_BACKEND_PORT}",
    ])

# Add production origins
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
if IS_PRODUCTION:
    CORS_ALLOWED_ORIGINS.extend([
        "https://app.zoea.studio",
        "https://zoea.studio",
        "https://zoea-app.onrender.com",  # Render default frontend URL
    ])

# Allow required headers for API requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow required methods including OPTIONS for CORS preflight
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Cache preflight requests for 1 hour
CORS_PREFLIGHT_MAX_AGE = 3600

# CSRF trusted origins - required for POST requests from different subdomains
CSRF_TRUSTED_ORIGINS = [
    f"http://localhost:{ZOEA_FRONTEND_PORT}",
    f"http://127.0.0.1:{ZOEA_FRONTEND_PORT}",
    f"http://local.zoea.studio:{ZOEA_FRONTEND_PORT}",
]

# exe.dev VM origins (when EXE_DEV_HOSTNAME is set)
if EXE_DEV_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.extend([
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz",
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz:{ZOEA_FRONTEND_PORT}",
        f"https://{EXE_DEV_HOSTNAME}.exe.xyz:{ZOEA_BACKEND_PORT}",
    ])

if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS.extend([
        "https://app.zoea.studio",
        "https://zoea.studio",
        "https://zoea-app.onrender.com",  # Render default frontend URL
    ])

# =============================================================================
# Production Security Settings
# =============================================================================
if IS_PRODUCTION:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Secure cookies - SameSite=None required for cross-origin requests
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'  # Required for cross-origin cookie sending
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'  # Required for cross-origin cookie sending

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True

# =============================================================================
# Django-Q2 Background Task Queue Configuration
# =============================================================================
Q_CLUSTER = {
    'name': 'ZoeaCore',
    'workers': 2,  # Start low, increase based on load
    'timeout': 600,  # 10 minutes - workflows can be long-running
    'retry': 900,  # 15 minutes - must be > timeout
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',  # Use PostgreSQL via Django ORM
    'save_limit': 100,  # Keep last 100 successful tasks
    'compress': True,  # Compress large payloads
    'catch_up': False,  # Don't run missed scheduled tasks on startup
    'label': 'Background Tasks',
}

# =============================================================================
# Django Sites Framework Configuration
# =============================================================================
# Required by django-allauth
SITE_ID = 1

# =============================================================================
# Django-allauth Configuration
# =============================================================================
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Account settings (using new django-allauth 65.x configuration)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}  # Allow login with username or email
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Require email verification before login
ACCOUNT_UNIQUE_EMAIL = True  # Ensure emails are unique

# Email confirmation settings
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Email confirmation link expires in 3 days
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Auto-login after email confirmation

# Login/Logout settings
ACCOUNT_LOGOUT_ON_GET = False  # Require POST to logout (security)
LOGIN_REDIRECT_URL = '/'  # Redirect after login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect after logout

# Custom adapter for organization initialization
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'

# Email backend configuration
# In development, use console backend to print emails to console
# In production, configure with SMTP settings
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production email settings (configure via environment variables)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Default from email
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@zoea.studio')

# Logging configuration
# Set LOG_LEVEL env var to control verbosity (DEBUG, INFO, WARNING, ERROR)
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'events': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'events.dispatcher': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'events.tasks': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'events.harness': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'email_gateway': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'chat': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
