# Generated by Django 6.0b1 on 2025-12-17 03:52
# Modified: Removed workspace FK

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text="Unique tool identifier from ToolRegistry (e.g., 'web_search')", max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this tool is enabled for the project')),
                ('config_overrides', models.JSONField(blank=True, default=dict, help_text='Tool-specific configuration overrides (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_configs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization that owns this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='tool_configs', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Project this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='tool_configs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Tool Configuration',
                'verbose_name_plural': 'Project Tool Configurations',
                'indexes': [models.Index(fields=['project', 'is_enabled'], name='agents_proj_project_8c1869_idx')],
                'unique_together': {('project', 'tool_name')},
            },
        ),
        migrations.CreateModel(
            name='ToolExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('input_summary', models.JSONField(default=dict, help_text='Sanitized summary of input parameters')),
                ('output_summary', models.JSONField(default=dict, help_text='Sanitized summary of output')),
                ('duration_ms', models.IntegerField(help_text='Execution time in ms', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Execution Log',
                'verbose_name_plural': 'Tool Execution Logs',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['organization', 'tool_name', '-executed_at'], name='agents_tool_organiz_1680f0_idx'), models.Index(fields=['project', '-executed_at'], name='agents_tool_project_a18558_idx')],
            },
        ),
    ]
