# Generated by Django 6.0.1 on 2026-01-24 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_wrappers', '0001_initial'),
        ('documents', '0016_rename_documents_d_project_4e7002_idx_documents_d_project_250bb8_idx_and_more'),
        ('events', '0004_alter_eventtrigger_event_type_scheduledevent'),
        ('execution', '0002_rename_execution_ex_organiz_55ebd6_idx_execution_e_organiz_288cbc_idx_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('platform_adapters', '0001_initial'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this route', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional description of this route's purpose")),
                ('destination_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('document', 'Document'), ('email', 'Email'), ('platform_reply', 'Reply to Platform')], help_text='Type of output destination', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this route is active')),
                ('channel_id', models.CharField(blank=True, help_text='Channel/room ID for Slack/Discord', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for webhook destinations')),
                ('template', models.TextField(blank=True, help_text='Output template (supports Jinja2-style variables)')),
                ('include_artifacts', models.BooleanField(default=True, help_text='Whether to include artifacts in the output')),
                ('format_type', models.CharField(default='text', help_text='Output format: text, json, markdown', max_length=20)),
                ('document_name_template', models.CharField(blank=True, default='output_{timestamp}', help_text='Template for document names', max_length=255)),
                ('output_filter', models.JSONField(blank=True, default=dict, help_text='Filter criteria for which outputs to dispatch')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority routes are executed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_output_routes', to=settings.AUTH_USER_MODEL)),
                ('document_folder', models.ForeignKey(blank=True, help_text='Folder to create documents in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_routes', to='documents.folder')),
                ('organization', models.ForeignKey(help_text='The organization that owns this route', on_delete=django.db.models.deletion.CASCADE, related_name='output_routes', to='organizations.organization')),
                ('platform_connection', models.ForeignKey(blank=True, help_text='Platform connection to use for output', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_routes', to='platform_adapters.platformconnection')),
                ('project', models.ForeignKey(blank=True, help_text='If set, route is default for this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_routes', to='projects.project')),
                ('trigger', models.ForeignKey(blank=True, help_text="If set, route is used for this trigger's outputs", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_routes', to='events.eventtrigger')),
            ],
            options={
                'verbose_name': 'Output Route',
                'verbose_name_plural': 'Output Routes',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Status details or error message')),
                ('destination_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('document', 'Document'), ('email', 'Email'), ('platform_reply', 'Reply to Platform')], max_length=20)),
                ('destination_info', models.JSONField(blank=True, default=dict, help_text='Destination details (channel, URL, etc.)')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='The payload that was/will be sent')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response from the destination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the dispatch was sent', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the dispatch completed', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='agent_wrappers.externalagentrun')),
                ('execution_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='execution.executionrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='organizations.organization')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='output_dispatch.outputroute')),
            ],
            options={
                'verbose_name': 'Dispatch Log',
                'verbose_name_plural': 'Dispatch Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outputroute',
            index=models.Index(fields=['organization', 'destination_type'], name='output_disp_organiz_af1be3_idx'),
        ),
        migrations.AddIndex(
            model_name='outputroute',
            index=models.Index(fields=['organization', 'is_enabled'], name='output_disp_organiz_b5c73b_idx'),
        ),
        migrations.AddIndex(
            model_name='outputroute',
            index=models.Index(fields=['trigger', 'is_enabled'], name='output_disp_trigger_5942fd_idx'),
        ),
        migrations.AddIndex(
            model_name='outputroute',
            index=models.Index(fields=['project', 'is_enabled'], name='output_disp_project_8f136f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['organization', '-created_at'], name='output_disp_organiz_214f17_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['route', '-created_at'], name='output_disp_route_i_07907b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['status'], name='output_disp_status_7ed13f_idx'),
        ),
    ]
