# Generated by Django 6.0b1 on 2025-11-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project'),
        ),
    ]
