# Generated by Django 6.0b1 on 2025-11-14 00:00
# Modified: Removed workspace FK (workspace model deleted)

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_project'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Workspace field and index removed - workspace model no longer exists
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', '-updated_at'], name='chat_conver_project_a83b6f_idx'),
        ),
    ]
