# Generated by Django 6.0b1 on 2025-11-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_project'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', '-updated_at'], name='chat_conver_project_a83b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', '-updated_at'], name='chat_conver_workspa_64b494_idx'),
        ),
    ]
