# Generated by Django 6.0b1 on 2025-12-16 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_workspace_and_more'),
        ('documents', '0010_alter_collection_options_alter_collection_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='artifacts',
            field=models.ForeignKey(blank=True, help_text='Collection of artifacts (code blocks, files, etc.) from this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='documents.documentcollection'),
        ),
    ]
