# Generated by Django 6.0.1 on 2026-01-24 01:15

import django.db.models.deletion
import platform_adapters.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_rename_execution_ex_organiz_55ebd6_idx_execution_e_organiz_288cbc_idx_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID used in webhook URLs', unique=True)),
                ('platform_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('email', 'Email'), ('webhook', 'Generic Webhook'), ('notion', 'Notion'), ('github', 'GitHub'), ('linear', 'Linear')], help_text='Type of external platform', max_length=20)),
                ('name', models.CharField(help_text='Human-readable name for this connection', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional description of this connection's purpose")),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Details about the current status (e.g., error message)')),
                ('webhook_secret', models.CharField(default=platform_adapters.models.generate_webhook_secret, help_text='Secret for validating incoming webhooks', max_length=64)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted credentials (API keys, tokens, etc.)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Platform-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was received', null=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Total messages received through this connection')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='If set, messages are scoped to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (received)'), ('outbound', 'Outbound (sent)')], default='inbound', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Processing status details or error message')),
                ('external_id', models.CharField(blank=True, help_text="Platform's unique identifier for this message", max_length=255)),
                ('channel_id', models.CharField(blank=True, help_text='Platform channel/room/thread identifier', max_length=255)),
                ('thread_id', models.CharField(blank=True, help_text='Thread/conversation identifier if applicable', max_length=255)),
                ('sender_id', models.CharField(blank=True, help_text="Platform's identifier for the sender", max_length=255)),
                ('sender_name', models.CharField(blank=True, help_text='Display name of the sender', max_length=255)),
                ('sender_email', models.EmailField(blank=True, help_text='Email address of the sender if available', max_length=254)),
                ('content', models.TextField(blank=True, help_text='Text content of the message')),
                ('content_type', models.CharField(default='text/plain', help_text='MIME type of the content', max_length=50)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment metadata')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional platform-specific metadata')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Original webhook payload')),
                ('platform_timestamp', models.DateTimeField(blank=True, help_text='When the message was created on the platform', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When we received the message')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='platform_adapters.platformconnection')),
                ('execution_run', models.ForeignKey(blank=True, help_text='ExecutionRun created for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_messages', to='execution.executionrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_messages', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_messages', to='projects.project')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['organization', 'platform_type'], name='platform_ad_organiz_3df783_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['connection_id'], name='platform_ad_connect_d73293_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['status'], name='platform_ad_status_3d19db_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['connection', '-received_at'], name='platform_ad_connect_ed7fac_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['organization', '-received_at'], name='platform_ad_organiz_760b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['status'], name='platform_ad_status_c9d10b_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['external_id'], name='platform_ad_externa_85179e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['channel_id'], name='platform_ad_channel_ccfd7d_idx'),
        ),
    ]
