"""
Service for creating Document records from tool-generated artifacts.

This module bridges the gap between tool outputs (which generate files) and
the document management system. When tools like image generators create files,
this service can create corresponding Document records and optionally add them
to artifact collections.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from django.core.files import File

from .models import Image

if TYPE_CHECKING:
    from organizations.models import Organization

    from workspaces.models import Workspace

logger = logging.getLogger(__name__)


class ToolArtifactService:
    """
    Service for creating Document records from tool-generated files.

    This service handles the conversion of file paths from tool outputs
    into proper Document records in the database.

    Example:
        service = ToolArtifactService(
            organization=org,
            workspace=workspace,
            created_by=user,
        )

        # Create an Image document from a generated file
        doc = service.create_image_from_path(
            file_path="/path/to/generated/image.png",
            title="Generated: A cozy coffee shop",
            mime_type="image/png",
        )
    """

    def __init__(
        self,
        *,
        organization: Organization,
        workspace: Workspace,
        created_by,
    ):
        """
        Initialize the service.

        Args:
            organization: Organization that owns the documents
            workspace: Workspace to associate documents with
            created_by: User who triggered the creation
        """
        self.organization = organization
        self.workspace = workspace
        self.created_by = created_by

    def create_image_from_path(
        self,
        file_path: str,
        title: str | None = None,
        mime_type: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> Image | None:
        """
        Create an Image document from a file path.

        Args:
            file_path: Path to the image file
            title: Display title for the document
            mime_type: MIME type of the image (e.g., "image/png")
            metadata: Additional metadata to store

        Returns:
            The created Image document, or None if creation failed
        """
        path = Path(file_path)

        if not path.exists():
            logger.warning(f"Image file does not exist: {file_path}")
            return None

        if not path.is_file():
            logger.warning(f"Path is not a file: {file_path}")
            return None

        try:
            # Create the Image document
            # Note: Image model doesn't support mime_type or metadata fields
            # Those are passed through for potential future use or logging
            with open(path, "rb") as f:
                django_file = File(f, name=path.name)

                image = Image.objects.create(
                    organization=self.organization,
                    project=self.workspace.project,
                    workspace=self.workspace,
                    name=title or path.stem,
                    description="Generated by AI tool",
                    created_by=self.created_by,
                    image_file=django_file,
                )

            logger.info(
                "Created Image document %d from tool artifact: %s",
                image.id,
                file_path,
            )
            return image

        except Exception as e:
            logger.error(f"Failed to create Image from {file_path}: {e}", exc_info=True)
            return None

    def _guess_mime_type(self, path: Path) -> str:
        """Guess MIME type from file extension."""
        ext = path.suffix.lower()
        mime_map = {
            ".png": "image/png",
            ".jpg": "image/jpeg",
            ".jpeg": "image/jpeg",
            ".gif": "image/gif",
            ".webp": "image/webp",
            ".svg": "image/svg+xml",
            ".bmp": "image/bmp",
        }
        return mime_map.get(ext, "image/png")

    def create_document_from_artifact(
        self,
        artifact_type: str,
        file_path: str,
        title: str | None = None,
        mime_type: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> Any | None:
        """
        Create a Document from an artifact based on its type.

        This is the main entry point for creating documents from tool artifacts.
        It dispatches to the appropriate handler based on artifact type.

        Args:
            artifact_type: Type of artifact ("image", "code", "document", "diagram")
            file_path: Path to the artifact file
            title: Display title for the document
            mime_type: MIME type of the file
            metadata: Additional metadata to store

        Returns:
            The created Document subclass instance, or None if creation failed
        """
        if artifact_type == "image":
            return self.create_image_from_path(
                file_path=file_path,
                title=title,
                mime_type=mime_type,
                metadata=metadata,
            )

        # TODO: Add support for other artifact types
        # - "code" -> Markdown or CodeDocument
        # - "document" -> appropriate Document subclass
        # - "diagram" -> D2Diagram or ExcalidrawDiagram

        logger.warning(f"Unsupported artifact type: {artifact_type}")
        return None


def create_documents_from_tool_artifacts(
    artifacts: list[dict[str, Any]],
    organization,
    workspace,
    created_by,
) -> list[tuple[dict[str, Any], Any]]:
    """
    Create Document records from a list of tool artifacts.

    Convenience function for processing multiple artifacts at once.

    Args:
        artifacts: List of artifact dictionaries with keys:
            - type: "image", "code", "document", "diagram"
            - path: File system path
            - mime_type: Optional MIME type
            - title: Optional display title
        organization: Organization that owns the documents
        workspace: Workspace to associate with
        created_by: User who triggered creation

    Returns:
        List of tuples (artifact_dict, created_document_or_none)
    """
    service = ToolArtifactService(
        organization=organization,
        workspace=workspace,
        created_by=created_by,
    )

    results = []
    for artifact in artifacts:
        doc = service.create_document_from_artifact(
            artifact_type=artifact.get("type", "unknown"),
            file_path=artifact.get("path", ""),
            title=artifact.get("title"),
            mime_type=artifact.get("mime_type"),
            metadata={"tool_artifact": artifact},
        )
        results.append((artifact, doc))

    return results
