# Generated by Django 6.0b1 on 2025-12-09 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0005_add_llm_config_fields'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_slug', models.CharField(help_text='Slug of the workflow that was executed', max_length=100)),
                ('run_id', models.CharField(default=uuid.uuid4, help_text='Unique identifier for this execution run', max_length=36, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current execution status', max_length=20)),
                ('inputs', models.JSONField(default=dict, help_text='Input parameters provided to the workflow')),
                ('outputs', models.JSONField(blank=True, help_text='Output results from the workflow execution', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('provider_model', models.CharField(blank=True, help_text="AI provider and model used (e.g., 'openai/gpt-4o')", max_length=100, null=True)),
                ('token_usage', models.JSONField(blank=True, help_text='Token usage breakdown (input_tokens, output_tokens, etc.)', null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Django-Q2 task ID for background execution', max_length=100, null=True)),
                ('created_by', models.ForeignKey(help_text='User who initiated this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this workflow run', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Project context for this run', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'workflow_slug'], name='workflows_w_organiz_df0f77_idx'), models.Index(fields=['organization', 'status'], name='workflows_w_organiz_fd4964_idx'), models.Index(fields=['created_by', '-created_at'], name='workflows_w_created_b4c268_idx')],
            },
        ),
    ]
