# Generated by Django 6.0b1 on 2025-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_workflowrun_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
