# Generated by Django 6.0b1 on 2025-12-16 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_migrate_clipboard_to_notebook'),
        ('workflows', '0003_add_updated_at_to_workflowrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='artifacts',
            field=models.ForeignKey(blank=True, help_text='Collection of artifacts (documents, files, etc.) produced by this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='documents.documentcollection'),
        ),
    ]
