# Generated by Django 6.0b1 on 2026-01-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_add_artifacts_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkflowRun",
        ),
    ]
