# Generated by Django 6.0.1 on 2026-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channel',
            new_name='channels_ch_organiz_1c5481_idx',
            old_name='channels_ch_organiz_6d3b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='channel',
            new_name='channels_ch_organiz_737f44_idx',
            old_name='channels_ch_organiz_b2a5c2_idx',
        ),
        migrations.RenameIndex(
            model_name='channelmessage',
            new_name='channels_ch_channel_2926df_idx',
            old_name='channels_ch_channel_3335c0_idx',
        ),
        migrations.RenameIndex(
            model_name='channelmessage',
            new_name='channels_ch_sender__741e7c_idx',
            old_name='channels_ch_sender__c12b51_idx',
        ),
    ]
