# Generated by Django 6.0b1 on 2025-12-06 06:15
# Modified: Removed workspace FK and clipboard context type

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("projects", "0004_add_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique session identifier",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("error", "Error"),
                        ],
                        default="initializing",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "gemini_store_id",
                    models.CharField(
                        blank=True,
                        help_text="Ephemeral Gemini File Search store ID for this session",
                        max_length=255,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Document"),
                            ("folder", "Folder Contents"),
                            ("collection", "Collection"),
                        ],
                        help_text="Type of document context (single, folder, collection)",
                        max_length=20,
                    ),
                ),
                (
                    "context_id",
                    models.PositiveIntegerField(
                        help_text="ID of the context item (document, folder, or collection)"
                    ),
                ),
                (
                    "document_ids",
                    models.JSONField(
                        default=list, help_text="Array of document IDs included in this session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(help_text="Session expiration time")),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional session title", max_length=200
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if session failed to initialize"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who started this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_sessions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RAGSessionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The message content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retrieved_documents",
                    models.JSONField(
                        default=list, help_text="Document sources retrieved for this response"
                    ),
                ),
                (
                    "thinking_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Agent reasoning steps (for assistant messages)",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="AI model used to generate this message",
                        max_length=100,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="RAG session this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="document_rag.ragsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(fields=["session_id"], name="document_ra_session_be4812_idx"),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(fields=["status"], name="document_ra_status_937ffb_idx"),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(
                fields=["organization", "-created_at"], name="document_ra_organiz_a78553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(
                fields=["created_by", "-created_at"], name="document_ra_created_25d254_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(fields=["expires_at"], name="document_ra_expires_2ca8c4_idx"),
        ),
        migrations.AddIndex(
            model_name="ragsessionmessage",
            index=models.Index(
                fields=["session", "created_at"], name="document_ra_session_2efbff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsessionmessage",
            index=models.Index(fields=["role"], name="document_ra_role_987eb0_idx"),
        ),
    ]
