# Generated by Django 6.0.1 on 2026-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_rag', '0002_ragsessionmessage_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsession',
            name='context_id',
            field=models.PositiveIntegerField(help_text='ID of the context item (document, folder, clipboard, or collection)'),
        ),
        migrations.AlterField(
            model_name='ragsession',
            name='context_type',
            field=models.CharField(choices=[('single', 'Single Document'), ('folder', 'Folder Contents'), ('collection', 'Collection')], help_text='Type of document context (single, folder, clipboard, collection)', max_length=20),
        ),
    ]
