# Generated by Django 6.0b1 on 2025-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_store_id',
            field=models.CharField(blank=True, help_text='Gemini File Search store ID for this project', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gemini_store_name',
            field=models.CharField(blank=True, help_text='Display name of the Gemini File Search store', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gemini_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time documents were synced to Gemini File Search', null=True),
        ),
    ]
