# Generated by Django 6.0b1 on 2025-12-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_gemini_store_id_project_gemini_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('aubergine', 'Aubergine'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('slate', 'Slate'), ('copper', 'Copper'), ('midnight', 'Midnight'), ('sunrise', 'Sunrise')], help_text='Color theme for the project UI', max_length=20, null=True),
        ),
    ]
