# Generated by Django 6.0b1 on 2025-12-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Project avatar image', null=True, upload_to='projects/avatars/'),
        ),
    ]
