# Generated by Django 6.0b1 on 2025-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Project-specific Gemini API key. Uses app default if not set.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='llm_model_id',
            field=models.CharField(blank=True, help_text='Model ID to use (e.g., gpt-4o, gemini-2.5-flash). Inherits from app defaults if not set.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='llm_provider',
            field=models.CharField(blank=True, help_text='LLM provider name (openai, gemini, ollama). Inherits from app defaults if not set.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='local_model_endpoint',
            field=models.URLField(blank=True, help_text='Endpoint URL for local models (Ollama, LM Studio)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Project-specific OpenAI API key. Uses app default if not set.', max_length=255, null=True),
        ),
    ]
