# Generated by Django 6.0b1 on 2025-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_llm_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_primary_header',
            field=models.BooleanField(default=False, help_text='Use theme primary color for app header background'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('amber-minimal', 'Amber Minimal'), ('claude', 'Claude'), ('corporate', 'Corporate'), ('modern-minimal', 'Modern'), ('nature', 'Nature'), ('slack', 'Slack'), ('twitter', 'Twitter'), ('cyberpunk', 'Cyberpunk'), ('red', 'Red'), ('summer', 'Summer'), ('notebook', 'Notebook')], help_text='Color theme for the project UI', max_length=20, null=True),
        ),
    ]
