# Generated by Django 6.0b1 on 2025-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0006_add_use_primary_header'),
    ]

    operations = [
        # Just add the field without any unique constraints
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug, auto-generated from name', max_length=100),
        ),
    ]
