# Generated by Django 6.0b1 on 2025-12-11 23:45

from django.db import migrations
from django.utils.text import slugify


def populate_project_slugs(apps, schema_editor):
    """Populate slug field for existing projects."""
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.filter(slug=''):
        base_slug = slugify(project.name) or 'unnamed'
        slug = base_slug
        counter = 1

        # Handle duplicates within the organization
        while Project.objects.filter(
            organization=project.organization,
            slug=slug
        ).exclude(pk=project.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        project.slug = slug
        project.save(update_fields=['slug'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear all slugs."""
    Project = apps.get_model('projects', 'Project')
    Project.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_slug_field'),
    ]

    operations = [
        migrations.RunPython(populate_project_slugs, reverse_populate),
    ]
