# Generated by Django 6.0b1 on 2025-12-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_populate_project_slugs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'name'), ('organization', 'slug')},
        ),
    ]
