# Generated by Django 6.0b1 on 2025-12-11

from django.db import migrations


def populate_project_canonical_emails(apps, schema_editor):
    """Populate canonical_email field for existing projects."""
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.filter(canonical_email=''):
        # Generate canonical email from slug and org slug
        org_slug = project.organization.slug
        canonical_email = f"{project.slug}.{org_slug}@zoea.studio"
        project.canonical_email = canonical_email
        project.save(update_fields=['canonical_email'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear all canonical emails."""
    Project = apps.get_model('projects', 'Project')
    Project.objects.update(canonical_email='')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_canonical_email_field'),
    ]

    operations = [
        migrations.RunPython(populate_project_canonical_emails, reverse_populate),
    ]
