# Generated by Django 6.0b1 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_populate_project_canonical_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='canonical_email',
            field=models.EmailField(
                blank=True,
                help_text='Auto-generated canonical email address (e.g., project-slug.org-slug@zoea.studio)',
                max_length=254,
                unique=True
            ),
        ),
    ]
