# Generated by Django 6.0b1 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_canonical_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_alias',
            field=models.CharField(
                blank=True,
                help_text="User-configurable email alias (e.g., 'bob' -> bob.org-slug@zoea.studio)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={
                ('organization', 'name'),
                ('organization', 'slug'),
                ('organization', 'email_alias'),
            },
        ),
    ]
