# Generated by Django 6.0.1 on 2026-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executionrun',
            new_name='execution_e_organiz_288cbc_idx',
            old_name='execution_ex_organiz_55ebd6_idx',
        ),
        migrations.RenameIndex(
            model_name='executionrun',
            new_name='execution_e_organiz_5f9a82_idx',
            old_name='execution_ex_organiz_1cc102_idx',
        ),
        migrations.RenameIndex(
            model_name='executionrun',
            new_name='execution_e_workflo_d3907f_idx',
            old_name='execution_ex_workfl_0c6d6d_idx',
        ),
        migrations.RenameIndex(
            model_name='executionrun',
            new_name='execution_e_source__922f6e_idx',
            old_name='execution_ex_source_139d33_idx',
        ),
    ]
