# Generated by Django 6.0b1 on 2026-01-08 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0015_add_word_and_spreadsheet_documents'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this trigger', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this trigger does')),
                ('event_type', models.CharField(choices=[('email_received', 'Email Received'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated')], db_index=True, help_text='Type of event that activates this trigger', max_length=50)),
                ('skills', models.JSONField(default=list, help_text="List of skill names to execute when triggered (e.g., ['extract-data', 'send-webhook'])")),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this trigger is active')),
                ('run_async', models.BooleanField(default=True, help_text='Execute in background task (recommended for production)')),
                ('filters', models.JSONField(blank=True, default=dict, help_text="Optional filters for event matching (e.g., {'document_type': 'markdown'})")),
                ('agent_config', models.JSONField(blank=True, default=dict, help_text='Additional configuration for the agent (e.g., custom instructions, max_steps)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this trigger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_triggers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this trigger', on_delete=django.db.models.deletion.CASCADE, related_name='event_triggers', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project scope. If not set, trigger applies to entire organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_triggers', to='projects.project')),
            ],
            options={
                'verbose_name': 'Event Trigger',
                'verbose_name_plural': 'Event Triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTriggerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=uuid.uuid4, help_text='Unique identifier for this execution run', max_length=36, unique=True)),
                ('source_type', models.CharField(help_text="Type of source that triggered this run (e.g., 'email_message', 'document')", max_length=50)),
                ('source_id', models.PositiveIntegerField(help_text='ID of the source object that triggered this run')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', help_text='Current execution status', max_length=20)),
                ('inputs', models.JSONField(default=dict, help_text='Event data passed to the skills')),
                ('outputs', models.JSONField(blank=True, help_text='Output results from skill execution', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('telemetry', models.JSONField(blank=True, help_text='Agent telemetry (token usage, timing, steps)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Django-Q2 task ID for background execution', max_length=100, null=True)),
                ('artifacts', models.ForeignKey(blank=True, help_text='Collection of artifacts produced by this trigger run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_trigger_runs', to='documents.documentcollection')),
                ('organization', models.ForeignKey(help_text='The organization that owns this run', on_delete=django.db.models.deletion.CASCADE, related_name='event_trigger_runs', to='organizations.organization')),
                ('trigger', models.ForeignKey(help_text='The trigger that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='events.eventtrigger')),
            ],
            options={
                'verbose_name': 'Event Trigger Run',
                'verbose_name_plural': 'Event Trigger Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventtrigger',
            index=models.Index(fields=['organization', 'event_type', 'is_enabled'], name='events_even_organiz_8b8a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtrigger',
            index=models.Index(fields=['project', 'event_type', 'is_enabled'], name='events_even_project_0ff814_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtriggerrun',
            index=models.Index(fields=['organization', 'trigger'], name='events_even_organiz_102de5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtriggerrun',
            index=models.Index(fields=['organization', 'status'], name='events_even_organiz_8a80af_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtriggerrun',
            index=models.Index(fields=['source_type', 'source_id'], name='events_even_source__9abaee_idx'),
        ),
    ]
