# Generated by Django 6.0.1 on 2026-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventtriggerrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtrigger',
            name='event_type',
            field=models.CharField(choices=[('email_received', 'Email Received'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('documents_selected', 'Documents Selected')], db_index=True, help_text='Type of event that activates this trigger', max_length=50),
        ),
    ]
