# Generated by Django 6.0.1 on 2026-01-24 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtrigger_event_type'),
        ('organizations', '0006_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtrigger',
            name='event_type',
            field=models.CharField(choices=[('email_received', 'Email Received'), ('document_created', 'Document Created'), ('document_updated', 'Document Updated'), ('documents_selected', 'Documents Selected'), ('chat_message', 'Chat Message'), ('slack_message', 'Slack Message'), ('discord_message', 'Discord Message'), ('webhook_received', 'Webhook Received'), ('notion_page_updated', 'Notion Page Updated'), ('scheduled_oneshot', 'Scheduled One-Shot'), ('scheduled_cron', 'Scheduled Recurring'), ('agent_completed', 'Agent Completed')], db_index=True, help_text='Type of event that activates this trigger', max_length=50),
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this scheduled event', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this scheduled event does')),
                ('schedule_type', models.CharField(choices=[('oneshot', 'One-Shot'), ('cron', 'Recurring (Cron)')], help_text='Type of schedule: one-shot or recurring cron', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='For one-shot events: when to execute (UTC)', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text="For cron events: cron expression (e.g., '0 9 * * 1-5' for weekdays at 9am)", max_length=100)),
                ('timezone_name', models.CharField(default='UTC', help_text="Timezone for interpreting the schedule (e.g., 'America/New_York')", max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional data to include in the event payload')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this scheduled event is active')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='Calculated next execution time (for scheduling queries)', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this event last fired', null=True)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='Total number of times this event has fired')),
                ('django_q_schedule_id', models.CharField(blank=True, help_text='ID of the Django-Q2 schedule (if using cron)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this scheduled event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this scheduled event', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='organizations.organization')),
                ('trigger', models.ForeignKey(help_text='The event trigger to execute when this schedule fires', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='events.eventtrigger')),
            ],
            options={
                'verbose_name': 'Scheduled Event',
                'verbose_name_plural': 'Scheduled Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='events_sche_organiz_367d20_idx'), models.Index(fields=['schedule_type', 'is_enabled'], name='events_sche_schedul_bb7481_idx'), models.Index(fields=['next_run_at'], name='events_sche_next_ru_40207d_idx')],
            },
        ),
    ]
