# Generated by Django 6.0b1 on 2025-11-14 00:00

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Workspace name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Workspace description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(help_text='User who created this workspace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent workspace (null for root workspaces)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workspaces.workspace')),
                ('project', models.ForeignKey(help_text='The project this workspace belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='projects.project')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'indexes': [models.Index(fields=['project'], name='workspaces__project_842ba9_idx'), models.Index(fields=['tree_id', 'lft'], name='workspaces_workspace_tree_941a')],
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
    ]
