# Generated by Django 6.0b1 on 2025-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_slug_field'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        # Just add the field without any unique constraints
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug, auto-generated from name', max_length=100),
        ),
    ]
