# Generated by Django 6.0b1 on 2025-12-11 23:45

from django.db import migrations
from django.utils.text import slugify


def populate_workspace_slugs(apps, schema_editor):
    """Populate slug field for existing workspaces."""
    Workspace = apps.get_model('workspaces', 'Workspace')

    for workspace in Workspace.objects.filter(slug=''):
        base_slug = slugify(workspace.name) or 'unnamed'
        slug = base_slug
        counter = 1

        # Handle duplicates within the project
        while Workspace.objects.filter(
            project=workspace.project,
            slug=slug
        ).exclude(pk=workspace.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        workspace.slug = slug
        workspace.save(update_fields=['slug'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear all slugs."""
    Workspace = apps.get_model('workspaces', 'Workspace')
    Workspace.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_add_slug_field'),
    ]

    operations = [
        migrations.RunPython(populate_workspace_slugs, reverse_populate),
    ]
