# Generated by Django 6.0b1 on 2025-12-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_populate_workspace_slugs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('project', 'parent', 'name'), ('project', 'slug')},
        ),
    ]
