# Generated by Django 6.0b1 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_add_slug_unique_constraint'),
    ]

    operations = [
        # Just add the field without any unique constraints
        migrations.AddField(
            model_name='workspace',
            name='canonical_email',
            field=models.EmailField(blank=True, help_text='Auto-generated canonical email address (e.g., workspace-slug.project-slug.org-slug@zoea.studio)', max_length=254),
        ),
    ]
