# Generated by Django 6.0b1 on 2025-12-11

from django.db import migrations


def populate_workspace_canonical_emails(apps, schema_editor):
    """Populate canonical_email field for existing workspaces."""
    Workspace = apps.get_model('workspaces', 'Workspace')

    for workspace in Workspace.objects.filter(canonical_email=''):
        # Generate canonical email from workspace, project, and org slugs
        project_slug = workspace.project.slug
        org_slug = workspace.project.organization.slug
        canonical_email = f"{workspace.slug}.{project_slug}.{org_slug}@zoea.studio"
        workspace.canonical_email = canonical_email
        workspace.save(update_fields=['canonical_email'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear all canonical emails."""
    Workspace = apps.get_model('workspaces', 'Workspace')
    Workspace.objects.update(canonical_email='')


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_add_canonical_email_field'),
    ]

    operations = [
        migrations.RunPython(populate_workspace_canonical_emails, reverse_populate),
    ]
