# Generated by Django 6.0b1 on 2025-11-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='The subscription tier for this account', max_length=50)),
                ('billing_email', models.EmailField(blank=True, help_text='Email address for billing and invoicing', max_length=254, null=True)),
                ('max_users', models.IntegerField(default=5, help_text='Maximum number of users allowed in this account')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Custom settings and preferences for this account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            bases=('organizations.organization',),
        ),
    ]
