# Generated by Django 6.0b1 on 2025-11-19 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0002_project_gemini_store_id_project_gemini_store_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('local', 'Local File System'), ('s3', 'AWS S3'), ('r2', 'Cloudflare R2')], help_text='Type of document source', max_length=50)),
                ('name', models.CharField(help_text='Display name for this source', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this source')),
                ('config', models.JSONField(help_text='Source-specific configuration (schema depends on source_type)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is actively used for document syncing')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time documents were synced from this source', null=True)),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Last time connection was tested', null=True)),
                ('last_test_success', models.BooleanField(blank=True, help_text='Result of last connection test', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization that owns this source', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Project this source belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='projects.project')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='sources_sou_organiz_c57118_idx'), models.Index(fields=['project', 'is_active'], name='sources_sou_project_40c600_idx'), models.Index(fields=['source_type'], name='sources_sou_source__5290ea_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
