# Generated by Django 6.0b1 on 2025-11-19 03:06

from django.db import migrations


def convert_working_directory_to_sources(apps, schema_editor):
    """
    Convert existing Project.working_directory values to Source records.

    For each project with a working_directory, create a local filesystem
    Source with the appropriate configuration.
    """
    Project = apps.get_model('projects', 'Project')
    Source = apps.get_model('sources', 'Source')

    for project in Project.objects.all():
        if project.working_directory:
            # Create a default local source for this project
            Source.objects.create(
                project=project,
                organization=project.organization,
                source_type='local',
                name='Default Documents',
                description=(
                    f'Migrated from working_directory field: {project.working_directory}'
                ),
                config={
                    'path': project.working_directory,
                    'pattern': '**/*.{md,pdf,png,jpg,jpeg,gif,csv,txt,d2}',
                    'recursive': True,
                    'follow_symlinks': False,
                },
                is_active=True,
            )


def reverse_conversion(apps, schema_editor):
    """
    Reverse the migration by deleting all sources.

    Note: This is a destructive operation and should only be used
    during development or testing.
    """
    Source = apps.get_model('sources', 'Source')
    Source.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('projects', '0002_project_gemini_store_id_project_gemini_store_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_working_directory_to_sources,
            reverse_code=reverse_conversion
        ),
    ]
