# Generated by Django 6.0.1 on 2026-01-24 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_rename_execution_ex_organiz_55ebd6_idx_execution_e_organiz_288cbc_idx_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this sandbox configuration', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional description of this configuration's purpose")),
                ('sandbox_type', models.CharField(choices=[('tmux', 'Tmux Session'), ('docker', 'Docker Container'), ('vm', 'Virtual Machine')], default='tmux', help_text='Type of execution environment', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default config for the organization')),
                ('docker_image', models.CharField(blank=True, default='python:3.12-slim', help_text='Docker image to use (for docker sandbox type)', max_length=500)),
                ('resource_limits', models.JSONField(blank=True, default=dict, help_text='Resource limits (cpu, memory, disk, timeout_seconds)')),
                ('allowed_paths', models.JSONField(blank=True, default=list, help_text='List of paths the sandbox can access')),
                ('workspace_base_path', models.CharField(blank=True, help_text='Base directory for sandbox workspaces', max_length=500)),
                ('environment_variables', models.JSONField(blank=True, default=dict, help_text='Environment variables to set in the sandbox')),
                ('shell_command', models.CharField(default='/bin/bash', help_text='Default shell to use', max_length=255)),
                ('network_enabled', models.BooleanField(default=True, help_text='Whether network access is allowed')),
                ('mount_project_readonly', models.BooleanField(default=False, help_text='Mount project directory as read-only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sandbox_configs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this config', on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sandbox Configuration',
                'verbose_name_plural': 'Sandbox Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', unique=True)),
                ('name', models.CharField(blank=True, help_text='Human-readable session name', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Creation'), ('creating', 'Creating'), ('ready', 'Ready'), ('running', 'Running'), ('error', 'Error'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Details about the current status (e.g., error message)')),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID (for docker type)', max_length=100)),
                ('tmux_session_name', models.CharField(blank=True, help_text='Tmux session name (for tmux type)', max_length=255)),
                ('vm_instance_id', models.CharField(blank=True, help_text='VM instance ID (for vm type)', max_length=255)),
                ('workspace_path', models.CharField(blank=True, help_text="Path to the session's workspace directory", max_length=500)),
                ('runtime_config', models.JSONField(blank=True, default=dict, help_text='Runtime configuration (frozen from config at creation)')),
                ('execution_count', models.PositiveIntegerField(default=0, help_text='Number of commands executed in this session')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='When the last activity occurred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the sandbox became ready', null=True)),
                ('terminated_at', models.DateTimeField(blank=True, help_text='When the sandbox was terminated', null=True)),
                ('config', models.ForeignKey(help_text='Configuration used to create this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='sandboxes.sandboxconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sandbox_sessions', to=settings.AUTH_USER_MODEL)),
                ('execution_run', models.ForeignKey(blank=True, help_text='ExecutionRun this session was created for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_sessions', to='execution.executionrun')),
                ('organization', models.ForeignKey(help_text='The organization that owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project this session is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Sandbox Session',
                'verbose_name_plural': 'Sandbox Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sandboxconfig',
            index=models.Index(fields=['organization', 'sandbox_type'], name='sandboxes_s_organiz_307521_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxconfig',
            index=models.Index(fields=['organization', 'is_default'], name='sandboxes_s_organiz_a1da2f_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['organization', 'status'], name='sandboxes_s_organiz_8c1356_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['project', 'status'], name='sandboxes_s_project_057f75_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxsession',
            index=models.Index(fields=['session_id'], name='sandboxes_s_session_5fad94_idx'),
        ),
    ]
