# Generated by Django 6.0b1 on 2025-12-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_conversation_workspace_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0004_add_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text='RFC 2822 thread identifier (usually first Message-ID)', max_length=512, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=998)),
                ('initiator_email', models.EmailField(help_text='Email address that started this thread', max_length=254)),
                ('recipient_address', models.EmailField(help_text='Inbound email address (e.g., inbox@mail.zoea.studio)', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', help_text='Thread status', max_length=20)),
                ('email_count', models.PositiveIntegerField(default=0, help_text='Cached count of emails in this thread')),
                ('first_email_at', models.DateTimeField(help_text='Timestamp of first email in thread')),
                ('last_email_at', models.DateTimeField(help_text='Timestamp of most recent email in thread')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(help_text='Linked chat conversation', on_delete=django.db.models.deletion.CASCADE, related_name='email_thread', to='chat.conversation')),
                ('initiator_user', models.ForeignKey(blank=True, help_text='User account matched to initiator email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_email_threads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this email thread belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project this email thread belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='projects.project')),
            ],
            options={
                'ordering': ['-last_email_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='RFC 2822 Message-ID header', max_length=512, unique=True)),
                ('in_reply_to', models.CharField(blank=True, help_text='RFC 2822 In-Reply-To header', max_length=512)),
                ('references', models.TextField(blank=True, help_text='RFC 2822 References header (space-separated Message-IDs)')),
                ('sender', models.EmailField(help_text='From email address', max_length=254)),
                ('recipient', models.EmailField(help_text='To email address', max_length=254)),
                ('subject', models.CharField(help_text='Email subject', max_length=998)),
                ('stripped_text', models.TextField(blank=True, help_text='Mailgun stripped-text (quoted parts removed)')),
                ('body_plain', models.TextField(blank=True, help_text='Full plain text body')),
                ('body_html', models.TextField(blank=True, help_text='Full HTML body')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Attachment metadata from Mailgun')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='All email headers')),
                ('raw_post_data', models.JSONField(blank=True, default=dict, help_text='Complete Mailgun POST data')),
                ('mailgun_timestamp', models.CharField(blank=True, help_text='Mailgun timestamp for signature verification', max_length=50)),
                ('mailgun_token', models.CharField(blank=True, help_text='Mailgun token for signature verification', max_length=100)),
                ('mailgun_signature', models.CharField(blank=True, help_text='Mailgun HMAC signature', max_length=256)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', help_text='Processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the webhook was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('chat_message', models.OneToOneField(blank=True, help_text='Created chat message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_message', to='chat.message')),
                ('organization', models.ForeignKey(help_text='Organization this email belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='organizations.organization')),
                ('sender_user', models.ForeignKey(blank=True, help_text='User account matched to sender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('email_thread', models.ForeignKey(blank=True, help_text='Parent email thread (set during processing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_gateway.emailthread')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['-last_email_at'], name='email_gatew_last_em_1ca6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['organization', '-last_email_at'], name='email_gatew_organiz_655c52_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['status', '-last_email_at'], name='email_gatew_status_7a6b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['initiator_email'], name='email_gatew_initiat_cf3ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status'], name='email_gatew_status_f15683_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['organization', 'status'], name='email_gatew_organiz_e15c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['sender'], name='email_gatew_sender_dcfea3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['received_at'], name='email_gatew_receive_84a5c8_idx'),
        ),
    ]
