# Generated by Django 6.0b1 on 2025-12-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_gateway', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this email belongs to (set during processing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='organizations.organization'),
        ),
    ]
