# Generated by Django 6.0b1 on 2025-12-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_gateway', '0003_emailattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailattachment',
            new_name='email_gatew_organiz_7335c0_idx',
            old_name='email_gatew_organiz_0a9fa8_idx',
        ),
        migrations.RenameIndex(
            model_name='emailattachment',
            new_name='email_gatew_email_m_40f06a_idx',
            old_name='email_gatew_email_me_cb2982_idx',
        ),
    ]
