# Generated by Django 6.0b1 on 2025-12-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_filedocument_system_folders'),
        ('email_gateway', '0004_rename_email_gatew_organiz_0a9fa8_idx_email_gatew_organiz_7335c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document created from this attachment (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='attachment_folder',
            field=models.ForeignKey(blank=True, help_text='Folder holding attachments for this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='documents.folder'),
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['document'], name='email_gatew_documen_7f5292_idx'),
        ),
    ]
