# Generated by Django 6.0b1 on 2025-12-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_add_attachments_collection'),
        ('email_gateway', '0006_remove_emailattachment_email_gatew_documen_7f5292_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='attachments',
            field=models.ForeignKey(blank=True, help_text='Collection of attachments for this email thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='documents.documentcollection'),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='attachment_folder',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use attachments collection instead. Folder holding attachments for this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='documents.folder'),
        ),
    ]
