# Generated by Django 6.0b1 on 2025-11-12 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='organizations.organization')),
                ('projects', models.ManyToManyField(blank=True, help_text='Projects associated with this collection', related_name='collections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('image_file', models.ImageField(help_text='Image file', upload_to='images/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, help_text='Image height in pixels', null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('pdf_file', models.FileField(help_text='PDF file', upload_to='pdfs/%Y/%m/%d/')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages in the PDF', null=True)),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('content', models.TextField(blank=True, help_text='Text content of the document')),
            ],
            options={
                'verbose_name': 'Text Document',
                'verbose_name_plural': 'Text Documents',
            },
            bases=('documents.document',),
        ),
        migrations.AddField(
            model_name='document',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collections this document belongs to', related_name='documents', to='documents.collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('has_header', models.BooleanField(default=True, help_text='Whether the CSV has a header row')),
                ('delimiter', models.CharField(default=',', help_text="Delimiter character (e.g., ',' or ';')", max_length=5)),
            ],
            options={
                'verbose_name': 'CSV Document',
                'verbose_name_plural': 'CSV Documents',
            },
            bases=('documents.textdocument',),
        ),
        migrations.CreateModel(
            name='D2Diagram',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('diagram_type', models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram')], help_text='Type of diagram', max_length=20)),
            ],
            options={
                'verbose_name': 'D2 Diagram',
                'verbose_name_plural': 'D2 Diagrams',
            },
            bases=('documents.textdocument',),
        ),
        migrations.CreateModel(
            name='Markdown',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
            ],
            options={
                'verbose_name': 'Markdown Document',
                'verbose_name_plural': 'Markdown Documents',
            },
            bases=('documents.textdocument',),
        ),
        migrations.CreateModel(
            name='ReactFlowDiagram',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('diagram_type', models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram')], help_text='Type of diagram', max_length=20)),
                ('react_flow_version', models.CharField(blank=True, help_text='React Flow library version used', max_length=20)),
            ],
            options={
                'verbose_name': 'React Flow Diagram',
                'verbose_name_plural': 'React Flow Diagrams',
            },
            bases=('documents.textdocument',),
        ),
    ]
