# Generated by Django 6.0b1 on 2025-11-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First remove the old many-to-many field
        migrations.RemoveField(
            model_name='collection',
            name='projects',
        ),
        # Then add the new foreign key fields
        migrations.AddField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this collection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='projects.project'),
        ),
        migrations.AddField(
            model_name='collection',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this collection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace'),
        ),
        # Then add indexes
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['project', '-created_at'], name='documents_c_project_f70120_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['workspace', '-created_at'], name='documents_c_workspa_b3aadf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', '-created_at'], name='documents_d_project_e576e0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-created_at'], name='documents_d_workspa_5cefbc_idx'),
        ),
        # Finally alter unique_together constraint
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('project', 'workspace', 'name')},
        ),
    ]
