# Generated by Django 6.0b1 on 2025-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_collection_unique_together_collection_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gemini_file_id',
            field=models.CharField(blank=True, help_text='Gemini File Search file ID for this document', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gemini_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this document was synced to Gemini File Search', null=True),
        ),
    ]
