# Generated by Django 6.0b1 on 2025-11-20 00:22
# Modified: Removed workspace FK operations

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_folder'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0002_project_gemini_store_id_project_gemini_store_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONCanvas',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('canvas_version', models.CharField(blank=True, help_text='JSON Canvas format version', max_length=20)),
            ],
            options={
                'verbose_name': 'JSON Canvas',
                'verbose_name_plural': 'JSON Canvases',
            },
            bases=('documents.textdocument',),
        ),
        migrations.CreateModel(
            name='MermaidDiagram',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('diagram_type', models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram')], help_text='Type of diagram', max_length=20)),
                ('mermaid_version', models.CharField(blank=True, help_text='Mermaid library version used', max_length=20)),
            ],
            options={
                'verbose_name': 'Mermaid Diagram',
                'verbose_name_plural': 'Mermaid Diagrams',
            },
            bases=('documents.textdocument',),
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_folder__b9ba49_idx',
            old_name='documents_d_folder_8cc0dc_idx',
        ),
        migrations.AlterField(
            model_name='d2diagram',
            name='diagram_type',
            field=models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram')], help_text='Type of diagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Folder containing this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this folder', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent folder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(help_text='Project that owns this folder', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='reactflowdiagram',
            name='diagram_type',
            field=models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram')], help_text='Type of diagram', max_length=20),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['tree_id', 'lft'], name='documents_folder_tree_id_lfd04'),
        ),
    ]
