# Generated by Django 6.0b1 on 2025-12-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentpreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcalidrawDiagram',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('diagram_type', models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram'), ('excalidraw', 'Excalidraw Diagram')], help_text='Type of diagram', max_length=20)),
                ('excalidraw_version', models.CharField(blank=True, help_text='Excalidraw library version used', max_length=20)),
            ],
            options={
                'verbose_name': 'Excalidraw Diagram',
                'verbose_name_plural': 'Excalidraw Diagrams',
            },
            bases=('documents.textdocument',),
        ),
        migrations.AlterField(
            model_name='d2diagram',
            name='diagram_type',
            field=models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram'), ('excalidraw', 'Excalidraw Diagram')], help_text='Type of diagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentpreview',
            name='document',
            field=models.ForeignKey(help_text='Document this preview belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='mermaiddiagram',
            name='diagram_type',
            field=models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram'), ('excalidraw', 'Excalidraw Diagram')], help_text='Type of diagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='reactflowdiagram',
            name='diagram_type',
            field=models.CharField(choices=[('d2', 'D2 Diagram'), ('react_flow', 'React Flow Diagram'), ('mermaid', 'Mermaid Diagram'), ('excalidraw', 'Excalidraw Diagram')], help_text='Type of diagram', max_length=20),
        ),
    ]
