# Generated by Django 6.0b1 on 2025-12-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_excalidraw_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System/hidden folder (excluded from normal listings)'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_system'], name='documents_f_is_syst_9616d1_idx'),
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='files/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename from the source', max_length=1024)),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255)),
            ],
            options={
                'verbose_name': 'File Document',
                'verbose_name_plural': 'File Documents',
            },
            bases=('documents.document',),
        ),
    ]
