# Generated by Django 6.0b1 on 2025-12-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_filedocument_system_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='YooptaDocument',
            fields=[
                ('textdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.textdocument')),
                ('yoopta_version', models.CharField(default='4.0', help_text='Yoopta-Editor version used', max_length=20)),
            ],
            options={
                'verbose_name': 'Yoopta Document',
                'verbose_name_plural': 'Yoopta Documents',
            },
            bases=('documents.textdocument',),
        ),
        migrations.RenameIndex(
            model_name='folder',
            new_name='documents_f_is_syst_907ccb_idx',
            old_name='documents_f_is_syst_9616d1_idx',
        ),
    ]
