# Generated by Django 6.0b1 on 2025-12-16 04:14
# Modified: Removed workspace FK and related operations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0009_add_yoopta_document'),
        ('organizations', '0006_alter_organization_slug'),
        ('projects', '0013_add_email_alias_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Collection (Legacy)', 'verbose_name_plural': 'Collections (Legacy)'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legacy_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_collections', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this collection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_collections', to='projects.project'),
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('artifact', 'Artifact'), ('attachment', 'Attachment'), ('notebook', 'Notebook')], default='artifact', help_text='Type of collection (artifact, attachment, or notebook)', max_length=20)),
                ('name', models.CharField(help_text='Collection name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the active collection (for notebooks)')),
                ('is_recent', models.BooleanField(default=False, help_text='Whether this collection is in the recent list (for notebooks)')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this collection was last activated', null=True)),
                ('sequence_head', models.BigIntegerField(default=0, help_text='Tracks the head index for deque-style item insertion')),
                ('sequence_tail', models.BigIntegerField(default=-1, help_text='Tracks the tail index for deque-style item insertion')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata (e.g., notepad content for notebooks)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='document_collections', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this collection (for notebooks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_document_collections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project this collection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_collections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Document Collection',
                'verbose_name_plural': 'Document Collections',
                'ordering': ['-activated_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCollectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(help_text='Type identifier for the node content', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Arbitrary node data')),
                ('preview_text', models.TextField(blank=True, help_text='Text preview for UI display')),
                ('preview_image', models.URLField(blank=True, help_text='Image preview URL')),
                ('origin_reference', models.CharField(blank=True, help_text='Reference to the origin of this node', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this node expires (for automatic cleanup)', null=True)),
                ('materialized_object_id', models.CharField(blank=True, help_text='ID of the materialized object', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_collection_nodes', to=settings.AUTH_USER_MODEL)),
                ('materialized_content_type', models.ForeignKey(blank=True, help_text='Content type of the materialized object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_virtual_collection_nodes', to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, help_text='Project this node belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_collection_nodes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Virtual Collection Node',
                'verbose_name_plural': 'Virtual Collection Nodes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(help_text='Relative ordering value supporting deque semantics')),
                ('direction_added', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Direction this item was added (left or right)', max_length=5)),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether this item is pinned')),
                ('object_id', models.CharField(blank=True, help_text='ID of the referenced object', max_length=255, null=True)),
                ('source_channel', models.CharField(choices=[('conversation', 'Conversation'), ('message', 'Message'), ('document', 'Document'), ('workflow', 'Workflow'), ('canvas', 'Canvas'), ('code', 'Code Snippet'), ('email', 'Email'), ('unknown', 'Unknown')], default='unknown', help_text='High-level origin hint for this item', max_length=32)),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the source')),
                ('preview', models.JSONField(blank=True, help_text='Custom preview data (e.g., chat bubble, diagram thumbnail)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_collection_items', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(help_text='The collection this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentcollection')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the referenced object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('virtual_node', models.ForeignKey(blank=True, help_text='Reference to a virtual node for transient items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='documents.virtualcollectionnode')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['project', 'collection_type'], name='documents_d_project_4e7002_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['project', 'owner'], name='documents_d_project_fe0664_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['collection_type', '-created_at'], name='documents_d_collect_4b9703_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('collection_type', 'notebook'), ('is_active', True)), fields=('project', 'owner'), name='unique_active_notebook_per_user'),
        ),
        migrations.AddIndex(
            model_name='virtualcollectionnode',
            index=models.Index(fields=['project', 'node_type'], name='documents_v_project_09daee_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualcollectionnode',
            index=models.Index(fields=['expires_at'], name='documents_v_expires_fcc2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollectionitem',
            index=models.Index(fields=['collection', 'position'], name='documents_d_collect_61ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollectionitem',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_595f06_idx'),
        ),
    ]
