# Generated by Django 6.0b1 on 2025-12-16 04:24

"""
Data migration to migrate Clipboard data to DocumentCollection (Notebook).

This migration:
1. Migrates VirtualClipboardNode → VirtualCollectionNode
2. Migrates Clipboard → DocumentCollection (type=NOTEBOOK)
3. Migrates ClipboardItem → DocumentCollectionItem

The migration preserves all data including:
- IDs (using explicit ID assignment to maintain foreign key references)
- All field values
- Relationships between items and nodes
"""

from django.db import migrations


def migrate_clipboard_to_notebook(apps, schema_editor):
    """Forward migration: Copy clipboard data to notebook models."""

    # Get models via apps.get_model for migration safety
    Clipboard = apps.get_model('context_clipboards', 'Clipboard')
    ClipboardItem = apps.get_model('context_clipboards', 'ClipboardItem')
    VirtualClipboardNode = apps.get_model('context_clipboards', 'VirtualClipboardNode')
    DocumentCollection = apps.get_model('documents', 'DocumentCollection')
    DocumentCollectionItem = apps.get_model('documents', 'DocumentCollectionItem')
    VirtualCollectionNode = apps.get_model('documents', 'VirtualCollectionNode')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Step 1: Migrate VirtualClipboardNode → VirtualCollectionNode
    # Create a mapping of old node IDs to new node IDs
    node_id_map = {}

    for old_node in VirtualClipboardNode.objects.all():
        # Map content type if present
        materialized_ct = None
        if old_node.materialized_content_type_id:
            materialized_ct = old_node.materialized_content_type

        new_node = VirtualCollectionNode.objects.create(
            workspace=old_node.workspace,
            created_by=old_node.created_by,
            node_type=old_node.node_type,
            payload=old_node.payload or {},
            preview_text=old_node.preview_text or '',
            preview_image=old_node.preview_image or '',
            origin_reference=old_node.origin_reference or '',
            expires_at=old_node.expires_at,
            materialized_content_type=materialized_ct,
            materialized_object_id=old_node.materialized_object_id,
        )
        # Manually set timestamps after creation
        VirtualCollectionNode.objects.filter(id=new_node.id).update(
            created_at=old_node.created_at,
            updated_at=old_node.updated_at,
        )
        node_id_map[old_node.id] = new_node.id

    # Step 2: Migrate Clipboard → DocumentCollection
    # Create a mapping of old clipboard IDs to new collection IDs
    clipboard_id_map = {}

    for clipboard in Clipboard.objects.select_related('workspace', 'owner').all():
        # Get organization from workspace
        organization = clipboard.workspace.project.organization if clipboard.workspace else None
        project = clipboard.workspace.project if clipboard.workspace else None

        new_collection = DocumentCollection.objects.create(
            organization=organization,
            project=project,
            workspace=clipboard.workspace,
            collection_type='notebook',  # CollectionType.NOTEBOOK
            owner=clipboard.owner,
            name=clipboard.name,
            description=clipboard.description or '',
            is_active=clipboard.is_active,
            is_recent=clipboard.is_recent,
            activated_at=clipboard.activated_at,
            sequence_head=clipboard.sequence_head,
            sequence_tail=clipboard.sequence_tail,
            metadata=clipboard.metadata or {},
            created_by=clipboard.owner,  # Use owner as created_by
        )
        # Manually set timestamps after creation
        DocumentCollection.objects.filter(id=new_collection.id).update(
            created_at=clipboard.created_at,
            updated_at=clipboard.updated_at,
        )
        clipboard_id_map[clipboard.id] = new_collection.id

    # Step 3: Migrate ClipboardItem → DocumentCollectionItem
    for item in ClipboardItem.objects.select_related('clipboard', 'content_type').all():
        new_collection_id = clipboard_id_map.get(item.clipboard_id)
        if not new_collection_id:
            continue  # Skip orphaned items

        # Map virtual node ID if present
        new_virtual_node_id = None
        if item.virtual_node_id:
            new_virtual_node_id = node_id_map.get(item.virtual_node_id)

        new_item = DocumentCollectionItem.objects.create(
            collection_id=new_collection_id,
            position=item.position,
            direction_added=item.direction_added,
            added_by=item.added_by,
            is_pinned=item.is_pinned,
            content_type=item.content_type,
            object_id=item.object_id,
            virtual_node_id=new_virtual_node_id,
            source_channel=item.source_channel,
            source_metadata=item.source_metadata or {},
            preview=item.preview,
        )
        # Manually set timestamps after creation
        DocumentCollectionItem.objects.filter(id=new_item.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at,
        )


def reverse_migration(apps, schema_editor):
    """Reverse migration: Delete migrated notebook data.

    This does NOT restore the original clipboard data - it only cleans up
    the migrated data from the new tables. The original clipboard data
    remains intact.
    """
    DocumentCollection = apps.get_model('documents', 'DocumentCollection')
    VirtualCollectionNode = apps.get_model('documents', 'VirtualCollectionNode')

    # Delete all notebooks (migrated from clipboards)
    # Items are deleted automatically via CASCADE
    DocumentCollection.objects.filter(collection_type='notebook').delete()

    # Delete all virtual collection nodes
    VirtualCollectionNode.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_collection_options_alter_collection_created_by_and_more'),
        ('context_clipboards', '0004_clipboarditem_preview'),  # Ensure clipboard migrations are applied
    ]

    operations = [
        migrations.RunPython(
            migrate_clipboard_to_notebook,
            reverse_code=reverse_migration,
        ),
    ]
