# Generated by Django 6.0b1 on 2025-12-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_migrate_clipboard_to_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this document is in the trash'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_folder_id',
            field=models.IntegerField(blank=True, help_text='Original folder ID before trashing (for restore)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='When this document was moved to trash', null=True),
        ),
    ]
