# Generated by Django 6.0b1 on 2025-12-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_trash_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcollectionitem',
            name='source_channel',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('message', 'Message'), ('document', 'Document'), ('workflow', 'Workflow'), ('canvas', 'Canvas'), ('code', 'Code Snippet'), ('tool', 'Tool Output'), ('email', 'Email'), ('unknown', 'Unknown')], default='unknown', help_text='High-level origin hint for this item', max_length=32),
        ),
    ]
