# Generated by Django 6.0b1 on 2025-12-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('xlsx_file', models.FileField(help_text='Excel spreadsheet file (.xlsx)', upload_to='xlsx/%Y/%m/%d/')),
                ('sheet_count', models.PositiveIntegerField(blank=True, help_text='Number of sheets in the spreadsheet', null=True)),
            ],
            options={
                'verbose_name': 'Spreadsheet Document',
                'verbose_name_plural': 'Spreadsheet Documents',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='WordDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('docx_file', models.FileField(help_text='Word document file (.docx)', upload_to='docx/%Y/%m/%d/')),
                ('paragraph_count', models.PositiveIntegerField(blank=True, help_text='Number of paragraphs in the document', null=True)),
            ],
            options={
                'verbose_name': 'Word Document',
                'verbose_name_plural': 'Word Documents',
            },
            bases=('documents.document',),
        ),
        migrations.RenameIndex(
            model_name='imagecaption',
            new_name='documents_i_image_i_9f6036_idx',
            old_name='doc_image_provider_model_idx',
        ),
    ]
