# Generated by Django 6.0.1 on 2026-01-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_add_word_and_spreadsheet_documents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentcollection',
            new_name='documents_d_project_250bb8_idx',
            old_name='documents_d_project_4e7002_idx',
        ),
        migrations.RenameIndex(
            model_name='documentcollection',
            new_name='documents_d_project_6bd8d3_idx',
            old_name='documents_d_project_fe0664_idx',
        ),
        migrations.RenameIndex(
            model_name='folder',
            new_name='documents_f_project_62075a_idx',
            old_name='documents_f_project_0d54ac_idx',
        ),
        migrations.RenameIndex(
            model_name='virtualcollectionnode',
            new_name='documents_v_project_446537_idx',
            old_name='documents_v_project_09daee_idx',
        ),
    ]
