# Generated by Django 6.0.1 on 2026-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_rename_documents_d_project_4e7002_idx_documents_d_project_250bb8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gemini_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of sync attempts (for retry tracking)'),
        ),
        migrations.AddField(
            model_name='document',
            name='gemini_sync_error',
            field=models.TextField(blank=True, help_text='Error message from last failed sync attempt', null=True),
        ),
    ]
